# Generated by Django 5.2.9 on 2026-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_unity_price_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARD', 'Cartão'), ('CASSH', 'Dinheiro')], default='PIX', max_length=20),
            preserve_default=False,
        ),
    ]
