# Generated by Django 5.2.9 on 2026-02-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARD', 'Cartão'), ('CASH', 'Dinheiro')], max_length=20, null=True),
        ),
    ]
