# Generated by Django 5.2.3 on 2025-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
    ]
