# Generated by Django 5.2.1 on 2025-05-27 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ml', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('title', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='establishment.ingredient')),
            ],
        ),
    ]
