# Generated by Django 5.2.3 on 2025-09-08 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_rename_unit_ingredient_unit_of_measure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('batch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(default='g', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establishment.ingredient')),
            ],
        ),
    ]
