# Generated by Django 5.2.1 on 2025-05-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ManyToManyField(related_name='final_cups', to='establishment.ingredient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_cups', to='establishment.recipient')),
            ],
        ),
    ]
