# Generated by Django 5.2.3 on 2025-11-17 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('ingredient', models.ManyToManyField(related_name='custom_cups', to='establishment.ingredient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_cups', to='establishment.recipient')),
            ],
        ),
    ]
