# Generated by Django 5.2.3 on 2025-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_customcup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcup',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
