# Generated by Django 5.2.1 on 2025-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0004_finalcup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_cup', models.ManyToManyField(related_name='combos', to='establishment.finalcup')),
            ],
        ),
    ]
