# Generated by Django 5.2.3 on 2025-12-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0005_alter_customcup_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit_of_measure',
        ),
    ]
