# Generated by Django 5.2.3 on 2025-12-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0006_remove_stock_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_addon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
