# Generated by Django 5.2.9 on 2026-02-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0009_dailyrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrevenue',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
