# Generated by Django 5.2.3 on 2025-11-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Establishment',
            new_name='establishment',
        ),
    ]
