# Generated by Django 5.2.9 on 2026-02-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_establishment_user_establishment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_management',
        ),
    ]
