# Generated by Django 5.2.9 on 2026-02-02 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('financial_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('MANUFACTURER', 'Fabricante'), ('DISTRIBUTOR', 'Distribuidor'), ('RETAILER', 'Varejista'), ('IMPORTER', 'Importador')], max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adress.address')),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.contact')),
            ],
        ),
    ]
